server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  username: root
  password: 268968&&ABc
  dbname: pisa_list
  max_idle_conns: 10
  max_open_conns: 100

jwt:
  secret: your_jwt_secret_key
  expire: 24 # hours

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0 